### ISSUE TITLE
Add type, value, etc. checking

### ISSUE THREAD

**Issue by nbrunett** [plfishertx/kerbacalc#3]
We can make the code more robust to unexpected behavior (e.g. integer math when we want floating point math) if we add type and value checking for methods that have inputs. The types would be pretty easy to do since the docstrings contain what type all arguments are supposed to be. Value checking may not make sense for everything but an example could be that the cardinal direction heading can only be specified as values between 0 and 2*pi.

With the checks in place we can also add "raise" statements that give useful messages on what is wrong. This commit (33ef56c) to the heading branch is an example of the value checking style I have in mind.

This would probably make the code uglier, and definitely longer, but it gets us some extra robustness where we have tighter control over the inputs the methods work with. Is this something you would want us to do @plfishertx or do you want to leave this extra infrastructure off? I think it would be a pretty easy task to get stine.py caught up with the checks it needs and then we would just keep this convention in mind as we continue.

**Comment by plfishertx** [comment]
That sounds good. If you want to start adding the type checking, I'll try to make time to get the rocket assembly code working for at least a one-stage rocket (instead of our current zero-stage "rock".) Then we can merge the branches.

**Comment by nbrunett** [comment]
Sorry that I'm jumping around quite a bit but I have a few variables that I want to check with you about. Should there be any value constraints on Itot and Isp in the Engine class? Maybe Itot and Isp cannot be less than zero. That's the only one I can think of for those.

Also, do you think I should restrict dt in Rocket.go to being greater than zero or should we leave that off? It would allow us to simulate "in-reverse" but I'm not sure if that would be useful haha.

**Comment by plfishertx** [comment]
I like the idea of allowing negative dt for running simulations in reverse.
Enforcing Itot and Isp > 0 is fine. I haven't had a chance to look at the
code for weeks because I still have no internet at home (I'm in the office
right now.) I am fed up with Comcast! More than two weeks and I still
haven't even been able to speak to a human being - just recordings which
keep assuring me "Your service is now restored" when it isn't!

plf

On Fri, Jun 5, 2015 at 9:27 PM, Nathan Brunetti notifications@github.com
wrote:

> Sorry that I'm jumping around quite a bit but I have a few variables that
> I want to check with you about. Should there be any value constraints on
> Itot and Isp in the Engine class? Maybe Itot and Isp cannot be less than
> zero. That's the only one I can think of for those.
> 
> Also, do you think I should restrict dt in Rocket.go to being greater than
> zero or should we leave that off? It would allow us to simulate
> "in-reverse" but I'm not sure if that would be useful haha.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/plfishertx/kerbacalc/issues/3#issuecomment-109494951.

## 

"It is difficult to say what is impossible, for the dream of yesterday is
the hope of today and the reality of tomorrow." - Robert H. Goddard

**Comment by nbrunett** [comment]
Alright, thanks for the feedback. I've committed my additions of type and value checking in stine.py in 385865f. I guess I'll close this issue since stine was really the extent of what I had in mind for this ticket.

Comcast is always a beast to deal with when it comes to getting any kind of service. Good luck.
